os: windows
sudo: false
language: node_js
node_js:
  - 4
  - 6
  - 8
# services:
#   - mongodb
before_script:
  - docker-compose up
script: npm run ci
after_script:
  - docker-compose down
notifications:
  email: false
